### CREATE A POST
POST http://localhost:3000/v1/api/write/todos/
Content-Type: application/json

{
  "title": "Backen App",
  "description": "Create a NestJS Backend App"
}


### delete
DELETE http://localhost:3000/api/v1/write/todos/1
Accept: application/json

###


### UPDATE A POST
PATCH http://localhost:3000/v1/api/write/todos/10
Content-Type: application/json

{
  "title": "999,",
  "description": "content"
}
